//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCPSoapClientForm.ServiceReference2SVS {
    using System.Runtime.Serialization;
    using System;
    using System.Xml.Serialization;

    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    //[System.Runtime.Serialization.DataContractAttribute(Name="CheckRequestData", Namespace="http://tempuri.org/")]
    //[System.SerializableAttribute()]
    [DataContract(Name = "CheckRequestData ", Namespace = "http://gucmp.ru/services/smev/pvk/resolutions/1.0.7")]
    [Serializable]
    [XmlRoot("CheckRequestData", Namespace = "http://gucmp.ru/services/smev/pvk/resolutions/1.0.7")]
    //public partial class CheckRequestData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
    public partial class CheckRequestData {

        [DataMember(Name = "CheckDate")]
        [XmlElement("CheckDate")]
        public DateTime CheckDate { get; set; }

        [DataMember(Name = "CheckPointCode", IsRequired = true)]
        [XmlElement("CheckPointCode", DataType = "string", Type = typeof(string))]
        public string CheckPointCode { get; set; }

        [DataMember(Name = "VehicleRegNumber", IsRequired = true)]
        [XmlElement("VehicleRegNumber", DataType = "string", Type = typeof(string))]
        public string VehicleRegNumber { get; set; }

        [DataMember(Name = "Direction", IsRequired = true)]
        [XmlElement("Direction", DataType = "int", Type = typeof(int))]
        public int Direction { get; set; }

        [DataMember(Name = "Latitude")]
        [XmlElement("Latitude", DataType = "decimal", Type = typeof(decimal))]
        public decimal Latitude { get; set; }

        [DataMember(Name = "Longitude")]
        [XmlElement("Longitude", DataType = "decimal", Type = typeof(decimal))]
        public decimal Longitude { get; set; }


        [DataMember(Name = "TotalWeight", IsRequired = true)]
        [XmlElement("TotalWeight", DataType = "decimal", Type = typeof(decimal))]
        public decimal TotalWeight { get; set; }

        [DataMember(Name = "AxlesCount", IsRequired = true)]
        [XmlElement("AxlesCount")]
        public int[] AxlesCount { get; set; }

        [DataMember(Name = "AxlesLoads", IsRequired = true)]
        [XmlElement("AxlesLoads")]
        public decimal[] AxlesLoads { get; set; }

        [DataMember(Name = "AxlesInvervals", IsRequired = true)]
        [XmlElement("AxlesInvervals")]
        public decimal[] AxlesInvervals { get; set; }

        [DataMember(Name = "TotalSize", IsRequired = true)]
        [XmlElement("TotalSize")]
        public CheckRequestDataTotalSize TotalSize { get; set; }
        
    }


    //[System.Runtime.Serialization.DataContractAttribute(Name="CheckRequestDataTotalSize", Namespace="http://tempuri.org/")]
    [DataContract(Name= "CheckRequestDataTotalSize")]
    [Serializable]
    public partial class CheckRequestDataTotalSize {

        [DataMember(Name = "Length")]
        [XmlElement("Length", DataType = "decimal", Type = typeof(decimal))]
        public decimal Length { get; set; }

        [DataMember(Name = "Width")]
        [XmlElement("Width", DataType = "decimal", Type = typeof(decimal))]
        public decimal Width { get; set; }


        /// <remarks/>
        [DataMember(Name = "Height")]
        [XmlElement("Height", DataType = "decimal", Type = typeof(decimal))]
        public decimal Height { get; set; }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt32", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt32 : System.Collections.Generic.List<System.Nullable<int>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfDecimal", Namespace="http://tempuri.org/", ItemName="decimal")]
    [System.SerializableAttribute()]
    public class ArrayOfDecimal : System.Collections.Generic.List<System.Nullable<decimal>> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="CheckResultDataList", Namespace="http://tempuri.org/", ItemName="CheckResultData")]
    [System.SerializableAttribute()]
    public class CheckResultDataList : System.Collections.Generic.List<WCPSoapClientForm.ServiceReference2SVS.CheckResultData> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckResultData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CheckResultData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCPSoapClientForm.ServiceReference2SVS.CheckResultDataCheckResultDataItemResolution ResolutionField;
        
        private int TripCountField;
        
        private int LeftTripCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RouteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCPSoapClientForm.ServiceReference2SVS.CheckResultDataCheckResultDataItemRouteCheck RouteCheckField;
        
        private System.DateTime DateFromField;
        
        private System.DateTime DateToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VehicleRegNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransporterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransporterAddressField;
        
        private decimal FullWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCPSoapClientForm.ServiceReference2SVS.CheckResultDataCheckResultDataItemDimensions DimensionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCPSoapClientForm.ServiceReference2SVS.ArrayOfDecimal AxlesLoadsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCPSoapClientForm.ServiceReference2SVS.ArrayOfDecimal AxlesInvervalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCPSoapClientForm.ServiceReference2SVS.ArrayOfInt32 AxlesWeelsExField;
        
        private WCPSoapClientForm.ServiceReference2SVS.CheckResultDataCheckResultDataItemShippingType ShippingTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WCPSoapClientForm.ServiceReference2SVS.CheckResultDataCheckResultDataItemResolution Resolution {
            get {
                return this.ResolutionField;
            }
            set {
                if ((object.ReferenceEquals(this.ResolutionField, value) != true)) {
                    this.ResolutionField = value;
                    this.RaisePropertyChanged("Resolution");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TripCount {
            get {
                return this.TripCountField;
            }
            set {
                if ((this.TripCountField.Equals(value) != true)) {
                    this.TripCountField = value;
                    this.RaisePropertyChanged("TripCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int LeftTripCount {
            get {
                return this.LeftTripCountField;
            }
            set {
                if ((this.LeftTripCountField.Equals(value) != true)) {
                    this.LeftTripCountField = value;
                    this.RaisePropertyChanged("LeftTripCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Route {
            get {
                return this.RouteField;
            }
            set {
                if ((object.ReferenceEquals(this.RouteField, value) != true)) {
                    this.RouteField = value;
                    this.RaisePropertyChanged("Route");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public WCPSoapClientForm.ServiceReference2SVS.CheckResultDataCheckResultDataItemRouteCheck RouteCheck {
            get {
                return this.RouteCheckField;
            }
            set {
                if ((object.ReferenceEquals(this.RouteCheckField, value) != true)) {
                    this.RouteCheckField = value;
                    this.RaisePropertyChanged("RouteCheck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime DateFrom {
            get {
                return this.DateFromField;
            }
            set {
                if ((this.DateFromField.Equals(value) != true)) {
                    this.DateFromField = value;
                    this.RaisePropertyChanged("DateFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime DateTo {
            get {
                return this.DateToField;
            }
            set {
                if ((this.DateToField.Equals(value) != true)) {
                    this.DateToField = value;
                    this.RaisePropertyChanged("DateTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string VehicleRegNumber {
            get {
                return this.VehicleRegNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleRegNumberField, value) != true)) {
                    this.VehicleRegNumberField = value;
                    this.RaisePropertyChanged("VehicleRegNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Transporter {
            get {
                return this.TransporterField;
            }
            set {
                if ((object.ReferenceEquals(this.TransporterField, value) != true)) {
                    this.TransporterField = value;
                    this.RaisePropertyChanged("Transporter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string TransporterAddress {
            get {
                return this.TransporterAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.TransporterAddressField, value) != true)) {
                    this.TransporterAddressField = value;
                    this.RaisePropertyChanged("TransporterAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public decimal FullWeight {
            get {
                return this.FullWeightField;
            }
            set {
                if ((this.FullWeightField.Equals(value) != true)) {
                    this.FullWeightField = value;
                    this.RaisePropertyChanged("FullWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public WCPSoapClientForm.ServiceReference2SVS.CheckResultDataCheckResultDataItemDimensions Dimensions {
            get {
                return this.DimensionsField;
            }
            set {
                if ((object.ReferenceEquals(this.DimensionsField, value) != true)) {
                    this.DimensionsField = value;
                    this.RaisePropertyChanged("Dimensions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public WCPSoapClientForm.ServiceReference2SVS.ArrayOfDecimal AxlesLoads {
            get {
                return this.AxlesLoadsField;
            }
            set {
                if ((object.ReferenceEquals(this.AxlesLoadsField, value) != true)) {
                    this.AxlesLoadsField = value;
                    this.RaisePropertyChanged("AxlesLoads");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public WCPSoapClientForm.ServiceReference2SVS.ArrayOfDecimal AxlesInvervals {
            get {
                return this.AxlesInvervalsField;
            }
            set {
                if ((object.ReferenceEquals(this.AxlesInvervalsField, value) != true)) {
                    this.AxlesInvervalsField = value;
                    this.RaisePropertyChanged("AxlesInvervals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public WCPSoapClientForm.ServiceReference2SVS.ArrayOfInt32 AxlesWeelsEx {
            get {
                return this.AxlesWeelsExField;
            }
            set {
                if ((object.ReferenceEquals(this.AxlesWeelsExField, value) != true)) {
                    this.AxlesWeelsExField = value;
                    this.RaisePropertyChanged("AxlesWeelsEx");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public WCPSoapClientForm.ServiceReference2SVS.CheckResultDataCheckResultDataItemShippingType ShippingType {
            get {
                return this.ShippingTypeField;
            }
            set {
                if ((this.ShippingTypeField.Equals(value) != true)) {
                    this.ShippingTypeField = value;
                    this.RaisePropertyChanged("ShippingType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckResultDataCheckResultDataItemResolution", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CheckResultDataCheckResultDataItemResolution : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentNumberField;
        
        private System.DateTime DocumentDateSignField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DocumentNumber {
            get {
                return this.DocumentNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentNumberField, value) != true)) {
                    this.DocumentNumberField = value;
                    this.RaisePropertyChanged("DocumentNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime DocumentDateSign {
            get {
                return this.DocumentDateSignField;
            }
            set {
                if ((this.DocumentDateSignField.Equals(value) != true)) {
                    this.DocumentDateSignField = value;
                    this.RaisePropertyChanged("DocumentDateSign");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckResultDataCheckResultDataItemRouteCheck", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CheckResultDataCheckResultDataItemRouteCheck : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodeToIntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodeToInt {
            get {
                return this.CodeToIntField;
            }
            set {
                if ((this.CodeToIntField.Equals(value) != true)) {
                    this.CodeToIntField = value;
                    this.RaisePropertyChanged("CodeToInt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckResultDataCheckResultDataItemDimensions", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CheckResultDataCheckResultDataItemDimensions : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal LengthField;
        
        private decimal WidthField;
        
        private decimal HeightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Length {
            get {
                return this.LengthField;
            }
            set {
                if ((this.LengthField.Equals(value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckResultDataCheckResultDataItemShippingType", Namespace="http://tempuri.org/")]
    public enum CheckResultDataCheckResultDataItemShippingType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        International = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Interregional = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Local = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WriteOfTripDataRequest", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class WriteOfTripDataRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentNumberField;
        
        private System.DateTime DocumentDateSignField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CheckPointCodeField;
        
        private int DirectionField;
        
        private decimal TotalWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCPSoapClientForm.ServiceReference2SVS.ArrayOfInt32 AxlesCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCPSoapClientForm.ServiceReference2SVS.ArrayOfDecimal AxlesLoadsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCPSoapClientForm.ServiceReference2SVS.ArrayOfDecimal AxlesInvervalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCPSoapClientForm.ServiceReference2SVS.CheckRequestDataTotalSize TotalSizeField;
        
        private System.DateTime TripDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DocumentNumber {
            get {
                return this.DocumentNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentNumberField, value) != true)) {
                    this.DocumentNumberField = value;
                    this.RaisePropertyChanged("DocumentNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime DocumentDateSign {
            get {
                return this.DocumentDateSignField;
            }
            set {
                if ((this.DocumentDateSignField.Equals(value) != true)) {
                    this.DocumentDateSignField = value;
                    this.RaisePropertyChanged("DocumentDateSign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CheckPointCode {
            get {
                return this.CheckPointCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CheckPointCodeField, value) != true)) {
                    this.CheckPointCodeField = value;
                    this.RaisePropertyChanged("CheckPointCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Direction {
            get {
                return this.DirectionField;
            }
            set {
                if ((this.DirectionField.Equals(value) != true)) {
                    this.DirectionField = value;
                    this.RaisePropertyChanged("Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal TotalWeight {
            get {
                return this.TotalWeightField;
            }
            set {
                if ((this.TotalWeightField.Equals(value) != true)) {
                    this.TotalWeightField = value;
                    this.RaisePropertyChanged("TotalWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public WCPSoapClientForm.ServiceReference2SVS.ArrayOfInt32 AxlesCount {
            get {
                return this.AxlesCountField;
            }
            set {
                if ((object.ReferenceEquals(this.AxlesCountField, value) != true)) {
                    this.AxlesCountField = value;
                    this.RaisePropertyChanged("AxlesCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public WCPSoapClientForm.ServiceReference2SVS.ArrayOfDecimal AxlesLoads {
            get {
                return this.AxlesLoadsField;
            }
            set {
                if ((object.ReferenceEquals(this.AxlesLoadsField, value) != true)) {
                    this.AxlesLoadsField = value;
                    this.RaisePropertyChanged("AxlesLoads");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public WCPSoapClientForm.ServiceReference2SVS.ArrayOfDecimal AxlesInvervals {
            get {
                return this.AxlesInvervalsField;
            }
            set {
                if ((object.ReferenceEquals(this.AxlesInvervalsField, value) != true)) {
                    this.AxlesInvervalsField = value;
                    this.RaisePropertyChanged("AxlesInvervals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public WCPSoapClientForm.ServiceReference2SVS.CheckRequestDataTotalSize TotalSize {
            get {
                return this.TotalSizeField;
            }
            set {
                if ((object.ReferenceEquals(this.TotalSizeField, value) != true)) {
                    this.TotalSizeField = value;
                    this.RaisePropertyChanged("TotalSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime TripDate {
            get {
                return this.TripDateField;
            }
            set {
                if ((this.TripDateField.Equals(value) != true)) {
                    this.TripDateField = value;
                    this.RaisePropertyChanged("TripDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WriteOffAnswerData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class WriteOffAnswerData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentNumberField;
        
        private System.DateTime DocumentDateSignField;
        
        private WCPSoapClientForm.ServiceReference2SVS.EnumWriteOffResolution WriteOffResolutionField;
        
        private int WriteOffResolutionToIntField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DocumentNumber {
            get {
                return this.DocumentNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentNumberField, value) != true)) {
                    this.DocumentNumberField = value;
                    this.RaisePropertyChanged("DocumentNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime DocumentDateSign {
            get {
                return this.DocumentDateSignField;
            }
            set {
                if ((this.DocumentDateSignField.Equals(value) != true)) {
                    this.DocumentDateSignField = value;
                    this.RaisePropertyChanged("DocumentDateSign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public WCPSoapClientForm.ServiceReference2SVS.EnumWriteOffResolution WriteOffResolution {
            get {
                return this.WriteOffResolutionField;
            }
            set {
                if ((this.WriteOffResolutionField.Equals(value) != true)) {
                    this.WriteOffResolutionField = value;
                    this.RaisePropertyChanged("WriteOffResolution");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int WriteOffResolutionToInt {
            get {
                return this.WriteOffResolutionToIntField;
            }
            set {
                if ((this.WriteOffResolutionToIntField.Equals(value) != true)) {
                    this.WriteOffResolutionToIntField = value;
                    this.RaisePropertyChanged("WriteOffResolutionToInt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumWriteOffResolution", Namespace="http://tempuri.org/")]
    public enum EnumWriteOffResolution : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WriteOffSuccessful = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WriteOffNotSuccessfulTrippOver = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WriteOffNotSuccessfulDocumentNotFound = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WriteOffNotSuccessfulWimNotFound = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WriteOffNotSuccessfulUnknownError = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2SVS.RASVSR")]
    public interface RASVSR {
        
        // CODEGEN: Контракт генерации сообщений с именем request из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RASVSR/Check", ReplyAction="*")]
        WCPSoapClientForm.ServiceReference2SVS.CheckResponse Check(WCPSoapClientForm.ServiceReference2SVS.CheckRequest CheckRequestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RASVSR/Check", ReplyAction="*")]
        System.Threading.Tasks.Task<WCPSoapClientForm.ServiceReference2SVS.CheckResponse> CheckAsync(WCPSoapClientForm.ServiceReference2SVS.CheckRequest CheckRequestData);
        
        // CODEGEN: Контракт генерации сообщений с именем WriteOff из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RASVSR/WriteOfTrip", ReplyAction="*")]
        WCPSoapClientForm.ServiceReference2SVS.WriteOfTripResponse WriteOfTrip(WCPSoapClientForm.ServiceReference2SVS.WriteOfTripRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RASVSR/WriteOfTrip", ReplyAction="*")]
        System.Threading.Tasks.Task<WCPSoapClientForm.ServiceReference2SVS.WriteOfTripResponse> WriteOfTripAsync(WCPSoapClientForm.ServiceReference2SVS.WriteOfTripRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Check", Namespace="http://tempuri.org/", Order=0)]
        public WCPSoapClientForm.ServiceReference2SVS.CheckRequestBody Body;
        
        public CheckRequest() {
        }
        
        public CheckRequest(WCPSoapClientForm.ServiceReference2SVS.CheckRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WCPSoapClientForm.ServiceReference2SVS.CheckRequestData request;
        
        public CheckRequestBody() {
        }
        
        public CheckRequestBody(WCPSoapClientForm.ServiceReference2SVS.CheckRequestData request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckResponse", Namespace="http://tempuri.org/", Order=0)]
        public WCPSoapClientForm.ServiceReference2SVS.CheckResponseBody Body;
        
        public CheckResponse() {
        }
        
        public CheckResponse(WCPSoapClientForm.ServiceReference2SVS.CheckResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WCPSoapClientForm.ServiceReference2SVS.CheckResultDataList CheckResult;
        
        public CheckResponseBody() {
        }
        
        public CheckResponseBody(WCPSoapClientForm.ServiceReference2SVS.CheckResultDataList CheckResult) {
            this.CheckResult = CheckResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WriteOfTripRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WriteOfTrip", Namespace="http://tempuri.org/", Order=0)]
        public WCPSoapClientForm.ServiceReference2SVS.WriteOfTripRequestBody Body;
        
        public WriteOfTripRequest() {
        }
        
        public WriteOfTripRequest(WCPSoapClientForm.ServiceReference2SVS.WriteOfTripRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WriteOfTripRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WCPSoapClientForm.ServiceReference2SVS.WriteOfTripDataRequest WriteOff;
        
        public WriteOfTripRequestBody() {
        }
        
        public WriteOfTripRequestBody(WCPSoapClientForm.ServiceReference2SVS.WriteOfTripDataRequest WriteOff) {
            this.WriteOff = WriteOff;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WriteOfTripResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WriteOfTripResponse", Namespace="http://tempuri.org/", Order=0)]
        public WCPSoapClientForm.ServiceReference2SVS.WriteOfTripResponseBody Body;
        
        public WriteOfTripResponse() {
        }
        
        public WriteOfTripResponse(WCPSoapClientForm.ServiceReference2SVS.WriteOfTripResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WriteOfTripResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WCPSoapClientForm.ServiceReference2SVS.WriteOffAnswerData WriteOfTripResult;
        
        public WriteOfTripResponseBody() {
        }
        
        public WriteOfTripResponseBody(WCPSoapClientForm.ServiceReference2SVS.WriteOffAnswerData WriteOfTripResult) {
            this.WriteOfTripResult = WriteOfTripResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RASVSRChannel : WCPSoapClientForm.ServiceReference2SVS.RASVSR, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RASVSRClient : System.ServiceModel.ClientBase<WCPSoapClientForm.ServiceReference2SVS.RASVSR>, WCPSoapClientForm.ServiceReference2SVS.RASVSR {
        
        public RASVSRClient() {
        }
        
        public RASVSRClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RASVSRClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RASVSRClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RASVSRClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCPSoapClientForm.ServiceReference2SVS.CheckResponse WCPSoapClientForm.ServiceReference2SVS.RASVSR.Check(WCPSoapClientForm.ServiceReference2SVS.CheckRequest request) {
            return base.Channel.Check(request);
        }
        
        public WCPSoapClientForm.ServiceReference2SVS.CheckResultDataList Check(WCPSoapClientForm.ServiceReference2SVS.CheckRequestData request) {
            WCPSoapClientForm.ServiceReference2SVS.CheckRequest inValue = new WCPSoapClientForm.ServiceReference2SVS.CheckRequest();
            inValue.Body = new WCPSoapClientForm.ServiceReference2SVS.CheckRequestBody();
            inValue.Body.request = request;
            WCPSoapClientForm.ServiceReference2SVS.CheckResponse retVal = ((WCPSoapClientForm.ServiceReference2SVS.RASVSR)(this)).Check(inValue);
            return retVal.Body.CheckResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCPSoapClientForm.ServiceReference2SVS.CheckResponse> WCPSoapClientForm.ServiceReference2SVS.RASVSR.CheckAsync(WCPSoapClientForm.ServiceReference2SVS.CheckRequest request) {
            return base.Channel.CheckAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCPSoapClientForm.ServiceReference2SVS.CheckResponse> CheckAsync(WCPSoapClientForm.ServiceReference2SVS.CheckRequestData request) {
            WCPSoapClientForm.ServiceReference2SVS.CheckRequest inValue = new WCPSoapClientForm.ServiceReference2SVS.CheckRequest();
            inValue.Body = new WCPSoapClientForm.ServiceReference2SVS.CheckRequestBody();
            inValue.Body.request = request;
            return ((WCPSoapClientForm.ServiceReference2SVS.RASVSR)(this)).CheckAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCPSoapClientForm.ServiceReference2SVS.WriteOfTripResponse WCPSoapClientForm.ServiceReference2SVS.RASVSR.WriteOfTrip(WCPSoapClientForm.ServiceReference2SVS.WriteOfTripRequest request) {
            return base.Channel.WriteOfTrip(request);
        }
        
        public WCPSoapClientForm.ServiceReference2SVS.WriteOffAnswerData WriteOfTrip(WCPSoapClientForm.ServiceReference2SVS.WriteOfTripDataRequest WriteOff) {
            WCPSoapClientForm.ServiceReference2SVS.WriteOfTripRequest inValue = new WCPSoapClientForm.ServiceReference2SVS.WriteOfTripRequest();
            inValue.Body = new WCPSoapClientForm.ServiceReference2SVS.WriteOfTripRequestBody();
            inValue.Body.WriteOff = WriteOff;
            WCPSoapClientForm.ServiceReference2SVS.WriteOfTripResponse retVal = ((WCPSoapClientForm.ServiceReference2SVS.RASVSR)(this)).WriteOfTrip(inValue);
            return retVal.Body.WriteOfTripResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCPSoapClientForm.ServiceReference2SVS.WriteOfTripResponse> WCPSoapClientForm.ServiceReference2SVS.RASVSR.WriteOfTripAsync(WCPSoapClientForm.ServiceReference2SVS.WriteOfTripRequest request) {
            return base.Channel.WriteOfTripAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCPSoapClientForm.ServiceReference2SVS.WriteOfTripResponse> WriteOfTripAsync(WCPSoapClientForm.ServiceReference2SVS.WriteOfTripDataRequest WriteOff) {
            WCPSoapClientForm.ServiceReference2SVS.WriteOfTripRequest inValue = new WCPSoapClientForm.ServiceReference2SVS.WriteOfTripRequest();
            inValue.Body = new WCPSoapClientForm.ServiceReference2SVS.WriteOfTripRequestBody();
            inValue.Body.WriteOff = WriteOff;
            return ((WCPSoapClientForm.ServiceReference2SVS.RASVSR)(this)).WriteOfTripAsync(inValue);
        }
    }
}
